/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _albumDAO = null
var albumDAO = function() {
	if(!_albumDAO) 
		_albumDAO = require("../dao/AlbumDAO")
	return new (_albumDAO)
}
var _albumTpl = null
var albumTpl = function() {
	if(!_albumTpl) 
		_albumTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/album.default.html"), "utf8")
	return _albumTpl
}

var AlbumAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("album", albumDAO, albumTpl, {"color":"#cbe"})
	},
	getThumbnailUri: function(data) {		
		return null
	} 
})

module.exports = AlbumAPI