/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var albumDAO = new (require("../dao/AlbumDAO"))

var AlbumAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("album", albumDAO, {"color":"#cbe"})
	},
	getThumbnailUri: function(data) {		
		return null
	} 
})

module.exports = AlbumAPI
