/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _albumNodeDAO = null
var albumNodeDAO = function() {
	if(!_albumNodeDAO) 
		_albumNodeDAO = require("../dao/AlbumNodeDAO")
	return new (_albumNodeDAO)
}
var _albumNodeTpl = null
var albumNodeTpl = function() {
	if(!_albumNodeTpl) 
		_albumNodeTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/albumNode.default.html"), "utf8")
	return _albumNodeTpl
}

var AlbumNodeAPI = NodeAPI.extend({
	constructor: function() {
		this.base("albumNode", albumNodeDAO, albumNodeTpl, {"color":"#ced"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = AlbumNodeAPI