/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _albumDAO = null
var albumDAO = function() {
	if(!_albumDAO) 
		_albumDAO = require("../dao/AlbumDAO")
	return new (_albumDAO)
}

var AlbumAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("album", albumDAO, {"color":"#cbe"})
	},
	getThumbnailUri: function(data) {		
		return null
	} 
})

module.exports = AlbumAPI