/* File autogenerated by craft  */

var merge = require("merge")
var fs = require('fs'); // require the filesystem api
var path = require("path")
var mustache = require("mustache")
var Base = require("basejs")

var AdminAPI = require("./AdminAPI")
var AppAPI = require("./AppAPI")
var ArticleAPI = require("./ArticleAPI")
var ImageAPI = require("./ImageAPI")
var VideoAPI = require("./VideoAPI")
var VoiceAPI = require("./VoiceAPI")
var JsonAPI = require("./JsonAPI")
var NetRadioAPI = require("./NetRadioAPI")
var UserAPI = require("./UserAPI")
var YouTubeVideoAPI = require("./YouTubeVideoAPI")
var FileAPI = require("./FileAPI")
var EntityAPI = require("./EntityAPI")

var API = {
	admin: new AdminAPI(),
	app: new AppAPI(),
	article: new ArticleAPI(),
	image: new ImageAPI(),
	video: new VideoAPI(),
	voice: new VoiceAPI(),
	json: new JsonAPI(),
	netRadio: new NetRadioAPI(),
	user: new UserAPI(),
	youTubeVideo: new YouTubeVideoAPI(),
	file: new FileAPI(),
	entity: new EntityAPI(),
}

module.exports = API