/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _appDAO = null
var appDAO = function() {
	if(!_appDAO) 
		_appDAO = require("../dao/AppDAO")
	return new (_appDAO)
}
var _appTpl = null
var appTpl = function() {
	if(!_appTpl) 
		_appTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/app.default.html"), "utf8")
	return _appTpl
}

var AppAPI = NodeAPI.extend({
	constructor: function() {
		this.base("app", appDAO, appTpl)
	},
	getThumbnailUri: function() {
		return null
	}
})

module.exports = AppAPI