/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _appDAO = null
var appDAO = function() {
	if(!_appDAO) 
		_appDAO = require("../dao/AppDAO")
	return new (_appDAO)
}

var AppAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("app", appDAO, {"color":"#fef"})
	},
	getThumbnailUri: function(data) {		
		return data.thumbnailUri
	}
})

module.exports = AppAPI