/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _articleDAO = null
var articleDAO = function() {
	if(!_articleDAO) 
		_articleDAO = require("../dao/ArticleDAO")
	return new (_articleDAO)
}
var _articleTpl = null
var articleTpl = function() {
	if(!_articleTpl) 
		_articleTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/article.default.html"), "utf8")
	return _articleTpl
}

var ArticleAPI = NodeAPI.extend({
	constructor: function() {
		this.base("article", articleDAO, articleTpl)
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ArticleAPI