/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _articleDAO = null
var articleDAO = function() {
	if(!_articleDAO) 
		_articleDAO = require("../dao/ArticleDAO")
	return new (_articleDAO)
}

var ArticleAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("article", articleDAO, {"color":"#eff"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ArticleAPI