/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _drawingDAO = null
var drawingDAO = function() {
	if(!_drawingDAO) 
		_drawingDAO = require("../dao/DrawingDAO")
	return new (_drawingDAO)
}

var DrawingAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("drawing", drawingDAO, {"color":"#fed"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = DrawingAPI