/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var drawingDAO = new (require("../dao/DrawingDAO"))

var DrawingAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("drawing", drawingDAO, {"color":"#fed"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = DrawingAPI
