/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _entityDAO = null
var entityDAO = function() {
	if(!_entityDAO) 
		_entityDAO = require("../dao/EntityDAO")
	return new (_entityDAO)
}
var _entityTpl = null
var entityTpl = function() {
	if(!_entityTpl) 
		_entityTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/entity.default.html"), "utf8")
	return _entityTpl
}

var EntityAPI = NodeAPI.extend({
	constructor: function() {
		this.base("entity", entityDAO, entityTpl, {"color":"#ced"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = EntityAPI