/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _entityDAO = null
var entityDAO = function() {
	if(!_entityDAO) 
		_entityDAO = require("../dao/EntityDAO")
	return new (_entityDAO)
}

var EntityAPI = NodeAPI.extend({
	constructor: function() {
		this.base("entity", entityDAO, {"color":"#ced"})
	},
	getThumbnailUri: function(data) {		
		return null
	},
	/**
	 * Promise-based get by entityID
	 * @param {string} id
	 */
	getByEidp: function(eid, type) {
		return this.findOnep({eid:eid, type:type})
	}
})

module.exports = EntityAPI