/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")
var _ = require("lodash")

var _favoriteDAO = null
var favoriteDAO = function() {
	if(!_favoriteDAO) 
		_favoriteDAO = require("../dao/FavoriteDAO")
	return new (_favoriteDAO)
}
var _favoriteTpl = null
var favoriteTpl = function() {
	if(!_favoriteTpl) 
		_favoriteTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/favorite.default.html"), "utf8")
	return _favoriteTpl
}

var FavoriteAPI = NodeAPI.extend({
	constructor: function() {
		this.base("favorite", favoriteDAO, favoriteTpl, {"color":"#cfd"})
	},
	getThumbnailUri: function(data) {		
		return null
	},
	star: function(userId, entityId, cb) {
		var date = new Date()
		var self = this
		this.findOne({userId: userId, entityId: entityId}, function(err, fav) {
			if(err) {
				cb(err);
			} else {
				if(fav) {
					// item exists...
					console.log(fav)
					fav.favorite = true
					self.update(fav._id, fav, cb)
				} else {
					// create it...
					self.create({userId: userId, entityId: entityId, favorite: true}, cb)
				}
			}
		})
	},
	unstar: function(userId, entityId, cb) {
		var date = new Date()
		var self = this
		this.findOne({userId: userId, entityId: entityId}, function(err, fav) {
			if(err) {
				cb(err);
			} else {
				if(fav) {
					// item exists...
					console.log(fav)
					fav.favorite = false
					self.update(fav._id, fav, cb)
				} else {
					// do nothing
					cb()
				}
			}
		})
	},
	starred: function(userId, entityId, cb) {
		this.countItems({userId: userId, entityId: entityId, favorite: true}, function(err, count) {
			if(err) cb(err);
			else cb(null, count>0)
		})

	},
	removeUser: function(userId, cb) {
		this.deleteItems({userId: userId}, cb)
	},
	removeEntity: function(entityId, cb) {
		this.deleteItems({entityId: entityId}, cb)
	},
	getUserFavorites: function(userId, cb) {
		this.find({userId: userId, favorite: true}, cb)
	},
	getUserFavoriteIDs: function(userId, cb) {
		this.getUserFavorites(userId, function(err, favs) {
			if(err) {
				cb(err)
			} else {
				cb(null, _.map(favs, function(f) { return f.entityId }))
			}
		})
	},
	getUserEntities: function(userId, cb) {
		this.find({userId: userId}, cb)
	},
	getUserEntityIDs: function(userId, cb) {
		this.getUserEntities(userId, function(err, favs) {
			if(err) {
				cb(err)
			} else {
				cb(null, _.map(favs, function(f) { return f.entityId }))
			}
		})
	},
})

module.exports = FavoriteAPI