/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var imageDAO = new (require("../dao/ImageDAO"))

var FileAPI = require("./FileAPI")

var ImageAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("image", imageDAO, {"color":"#ffd"})
		this.fapi = new FileAPI()
	},
	getThumbnailUri: function(data) {	
		return this.thumbFromUUID(data.imageUUID)
	},
	get: function(id, next) {
		var self = this
		this.base(id, function(err, image) {
			if(err) next(err);
			else if(!image) next(null, null);
			else {
				self.fapi.getByUuid(image.imageUUID, function(err, img) {
					image.image = img
					next(null, image)
				})
			}
		})
	}

})

module.exports = ImageAPI
