/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _imageDAO = null
var imageDAO = function() {
	if(!_imageDAO) 
		_imageDAO = require("../dao/ImageDAO")
	return new (_imageDAO)
}
var _imageTpl = null
var imageTpl = function() {
	if(!_imageTpl) 
		_imageTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/image.default.html"), "utf8")
	return _imageTpl
}

var ImageAPI = NodeAPI.extend({
	constructor: function() {
		this.base("image", imageDAO, imageTpl)
	},
	getThumbnailUri: function() {
		return null
	}
})

module.exports = ImageAPI