/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")
var EntityAPI = require("./EntityAPI")

var eapi = new EntityAPI()

var IndexedNodeAPI = NodeAPI.extend({
	constructor: function(name, dao, tpl) {
		this.base(name, dao, tpl)
	},
	create: function(data, next) {
		console.log("IndexedNodeApi.create: ", this.name, data)
		this.base(data, next)
		//console.log("create: ", this.name, data)
		//this.dao().create(data, next)
	},
	set: function(id, data, next) {
		console.log("IndexedNodeApi.set: ", this.name, id, data)
		this.base(id, data, next)
		// this.dao().set(id, data, next)
	},
	update: function(id, data, next) {
		console.log("IndexedEntityApi.update: ", this.name, id, data)
		this.base(id, data, next)
		//var newData = merge({_id:id}, data)
		//this.dao().update(newData, next)
	},
	delete: function(id, next) {
		console.log("IndexedNodeApi.delete: ", this.name, id)
		this.base(id, next)
		// this.dao().remove(id, next)
	},
	deleteItems: function(data, next) {
		console.log("IndexedNodeApi.deleteItems: ", this.name, data)
		this.base(data, next)
		// this.dao().removeItems(data, next)
	},	
})

module.exports = IndexedNodeAPI