/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")
var EntityAPI = require("./EntityAPI")

var eapi = new EntityAPI()

var findNodeByEid = function(type, eid, next) {
	eapi.findOne({eid:eid, type:type}, next)
}

var IndexedNodeAPI = NodeAPI.extend({
	constructor: function(name, dao, tpl) {
		this.base(name, dao, tpl)
	},
	create: function(data, next) {		
		var self = this
		this.base(data, function(err, res) {
			if(err) {
				return next(err)
			} else {
				var rr = res[0]
				var ent = {
					ownerAdminId: rr.ownerAdminId,
					title: rr.title,
					description: rr.description,
					tags: rr.tags,
					type: self.name,
					eid: parseInt(rr._id)
				} 
				console.log("ent:", ent)
				eapi.create(ent, function(err2, res2) {
					if(err2) {
						return next(err2)
					}
					next(null, res)
				})
			}
		})
	},
	set: function(id, data, next) {
		var self = this
		this.base(id, data, function(err, res) {
			if(err) { return next(err) }
			findNodeByEid(self.name, parseInt(id), function(err2, res2) {
				var ent = {
					title: data.title,
					description: data.description,
					tags: data.tags,
					type: self.name,
				} 				
				var _id = res2._id
				eapi.set(_id, ent, function(err2, res2) {
					if(err2) {
						return next(err2)
					}
					next(null, res)
				})

			})
		})
	},
	update: function(id, data, next) {
		var self = this
		this.base(id, data, function(err, res) {
			if(err) { return next(err) }
			findNodeByEid(self.name, parseInt(id), function(err2, res2) {
				var ent = {
					title: data.title,
					description: data.description,
					tags: data.tags,
					type: self.name,
				} 				
				var _id = res2._id
				eapi.update(_id, ent, function(err2, res2) {
					if(err2) {
						return next(err2)
					}
					next(null, res)
				})

			})
		})
	},
	delete: function(id, next) {
		var self = this
		this.base(id, function(err, res) {
			if(err) { return next(err) }
			else {
				var dt = {type:self.name, eid:parseInt(id)}
				// console.log("IndexedNodeApi.delete: ", dt)
				eapi.deleteItems(dt, function(err2, res2) {
					if(err2) { return next(err2) }
					next(null, res)
				})
			}
		})
	},
	// TODO delete also entities
	deleteItems: function(data, next) {
		console.log("IndexedNodeApi.deleteItems: ", this.name, data)
		this.base(data, next)
		// this.dao().removeItems(data, next)
	},	
})

module.exports = IndexedNodeAPI