/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _jsonDAO = null
var jsonDAO = function() {
	if(!_jsonDAO) 
		_jsonDAO = require("../dao/JsonDAO")
	return new (_jsonDAO)
}

var JsonAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("json", jsonDAO, {"color":"#fed"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = JsonAPI