/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _jsonDAO = null
var jsonDAO = function() {
	if(!_jsonDAO) 
		_jsonDAO = require("../dao/JsonDAO")
	return new (_jsonDAO)
}
var _jsonTpl = null
var jsonTpl = function() {
	if(!_jsonTpl) 
		_jsonTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/json.default.html"), "utf8")
	return _jsonTpl
}

var JsonAPI = NodeAPI.extend({
	constructor: function() {
		this.base("json", jsonDAO, jsonTpl)
	},
	getThumbnailUri: function() {
		return null
	}
})

module.exports = JsonAPI