/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var jsonDAO = new (require("../dao/JsonDAO"))

var JsonAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("json", jsonDAO, {"color":"#fed"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = JsonAPI
