/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var layoutDAO = new (require("../dao/LayoutDAO"))
	
var LayoutAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("layout", layoutDAO, {"color":"#fed"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = LayoutAPI
