/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _layoutDAO = null
var layoutDAO = function() {
	if(!_layoutDAO) 
		_layoutDAO = require("../dao/LayoutDAO")
	return new (_layoutDAO)
}

var LayoutAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("layout", layoutDAO, {"color":"#fed"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = LayoutAPI