/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var locationDAO = new(require("../dao/LocationDAO"))

var LocationAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("location", locationDAO, {"color":"#bcb"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = LocationAPI
