/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _locationDAO = null
var locationDAO = function() {
	if(!_locationDAO) 
		_locationDAO = require("../dao/LocationDAO")
	return new (_locationDAO)
}

var LocationAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("location", locationDAO, {"color":"#bcb"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = LocationAPI