/* File autogenerated by craft  */

var path = require("path")
var NodeAPI = require("./NodeAPI")

var _logDAO = null
var logDAO = function() {
	if(!_logDAO) 
		_logDAO = require("../dao/LogDAO")
	return new (_logDAO)
}

var LogAPI = NodeAPI.extend({
	constructor: function() {
		this.base("log", logDAO, {"color":"#cfd"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = LogAPI