/* File autogenerated by craft  */

var path = require("path")
var NodeAPI = require("./NodeAPI")

var logDAO = new(require("../dao/LogDAO"))

var LogAPI = NodeAPI.extend({
	constructor: function() {
		this.base("log", logDAO, {"color":"#cfd"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = LogAPI
