/* File autogenerated by craft  */

var path = require("path")
var NodeAPI = require("./NodeAPI")

var _logDAO = null
var logDAO = function() {
	if(!_logDAO) 
		_logDAO = require("../dao/LogDAO")
	return new (_logDAO)
}
var _logTpl = null
var logTpl = function() {
	if(!_logTpl) 
		_logTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/log.default.html"), "utf8")
	return _logTpl
}

var LogAPI = NodeAPI.extend({
	constructor: function() {
		this.base("log", logDAO, logTpl, {"color":"#cfd"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = LogAPI