/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _netRadioDAO = null
var netRadioDAO = function() {
	if(!_netRadioDAO) 
		_netRadioDAO = require("../dao/NetRadioDAO")
	return new (_netRadioDAO)
}

var NetRadioAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("netRadio", netRadioDAO, {"color":"#def"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = NetRadioAPI