/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")
var EntityAPI = require("./EntityAPI")

var playlistNodeDAO = new (require("../dao/PlaylistNodeDAO"))

var PlaylistNodeAPI = NodeAPI.extend({
	constructor: function() {
		this.base("playlistNode", playlistNodeDAO, {"color":"#ced"})
		this.eapi = new EntityAPI()
	},
	getThumbnailUri: function(data) {		
		return null
	},
	// keeps only one entry of each value type (adminId, nodeId)
	addToPlaylist: function(playlistId, nodeId, next) {
		var self = this
		this.eapi.getp(nodeId).done(function(data) {
			if(!data) {
				next(new Error("Node not found!"))
			} else {
				self.removeFromPlaylist(playlistId, nodeId, function(err, res) {
					if(err) next(err);
					else {
						var entry = {
							playlistId: playlistId,
							nodeId: nodeId,
							entityType: data.type,
							entityId: data.eid
						}
						self.create(entry, next)	
					}
				})
				
			}
		})

	},
	removeFromPlaylist: function(playlistId, nodeId, next) {
		this.deleteItems({playlistId: playlistId, nodeId:nodeId}, next)
	},
	getContents: function(playlistId, next) {
		this.find({playlistId: playlistId}, next)
	}
})

module.exports = PlaylistNodeAPI
