/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var playlistDAO = new (require("../dao/PlaylistDAO"))

var PlaylistAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("playlist", playlistDAO, {"color":"#fed"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = PlaylistAPI
