/* File autogenerated by craft  */

module.exports = function(app, api) {


	// helper function to return the results
	var out = function(res, err, rr) {
    	if(!err) {
    		res.json(rr)
    	} else {
    		console.error(err)
    		res.json({ error: err })
    	}
	}

	var renderView = function(name, req, res) {
		api[name].get(req.params.id, function(err, rr) {
	    	if(!err) {
	    		if(!rr) {
	    			res.status(404)
	    			res.end('not found')
	    			return
	    		}
				var tpl = api[name].renderView(rr)
    			res.send(tpl)
    		} else {
    			console.error(err)
    			res.status(500);
    			res.end('error')
    		}
	  	})	
	}		

	var renderPreview = function(name, req, res) {
		api[name].get(req.params.id, function(err, rr) {
	    	if(!err) {
	    		if(!rr) {
	    			res.status(404)
	    			res.end('not found')
	    			return
	    		}
				var tpl = api[name].renderPreview(rr)
    			res.send(tpl)
    		} else {
    			console.error(err)
    			res.status(500);
    			res.end('error')
    		}
	  	})	
	}		

	// common functionality for all API calls
	// returned data are in JSON
	app.use("/api", function(req, res, next) {
		res.type('application/json');
		next()
	})

	// generated REST wrappers for entity 'admin'

	// api.admin.find
	app.get('/api/admin/search', function(req, res) {
	 	api.admin.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.admin.count
	app.get('/api/admin/count', function(req, res) {
	 	api.admin.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.admin.get
	app.get('/api/admin/:id', function(req, res) {
	 	api.admin.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.admin.delete
	app.delete('/api/admin/:id', function(req, res) {
	 	api.admin.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.admin.update
	app.put('/api/admin/:id', function(req, res) {
		//api.admin.update(req.params.id, req.body, function(err, rr) {
		api.admin.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.admin.create
	app.post('/api/admin/new', function(req, res) {
		api.admin.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/admin',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/admin.png" });
		res.end();
	});

	app.get('/admin/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/admin" });
		res.end();
	});

	app.get('/admin/:id/view',function(req,res) {
		// return default view...		
		renderView("admin", req, res)
	});

	app.get('/admin/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("admin", req, res)
	});

	// generated REST wrappers for entity 'app'

	// api.app.find
	app.get('/api/app/search', function(req, res) {
	 	api.app.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.app.count
	app.get('/api/app/count', function(req, res) {
	 	api.app.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.app.get
	app.get('/api/app/:id', function(req, res) {
	 	api.app.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.app.delete
	app.delete('/api/app/:id', function(req, res) {
	 	api.app.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.app.update
	app.put('/api/app/:id', function(req, res) {
		//api.app.update(req.params.id, req.body, function(err, rr) {
		api.app.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.app.create
	app.post('/api/app/new', function(req, res) {
		api.app.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/app',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/app.png" });
		res.end();
	});

	app.get('/app/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/app" });
		res.end();
	});

	app.get('/app/:id/view',function(req,res) {
		// return default view...		
		renderView("app", req, res)
	});

	app.get('/app/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("app", req, res)
	});

	// generated REST wrappers for entity 'article'

	// api.article.find
	app.get('/api/article/search', function(req, res) {
	 	api.article.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.article.count
	app.get('/api/article/count', function(req, res) {
	 	api.article.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.article.get
	app.get('/api/article/:id', function(req, res) {
	 	api.article.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.article.delete
	app.delete('/api/article/:id', function(req, res) {
	 	api.article.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.article.update
	app.put('/api/article/:id', function(req, res) {
		//api.article.update(req.params.id, req.body, function(err, rr) {
		api.article.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.article.create
	app.post('/api/article/new', function(req, res) {
		api.article.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/article',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/article.png" });
		res.end();
	});

	app.get('/article/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/article" });
		res.end();
	});

	app.get('/article/:id/view',function(req,res) {
		// return default view...		
		renderView("article", req, res)
	});

	app.get('/article/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("article", req, res)
	});

	// generated REST wrappers for entity 'image'

	// api.image.find
	app.get('/api/image/search', function(req, res) {
	 	api.image.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.image.count
	app.get('/api/image/count', function(req, res) {
	 	api.image.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.image.get
	app.get('/api/image/:id', function(req, res) {
	 	api.image.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.image.delete
	app.delete('/api/image/:id', function(req, res) {
	 	api.image.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.image.update
	app.put('/api/image/:id', function(req, res) {
		//api.image.update(req.params.id, req.body, function(err, rr) {
		api.image.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.image.create
	app.post('/api/image/new', function(req, res) {
		api.image.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/image',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/image.png" });
		res.end();
	});

	app.get('/image/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/image" });
		res.end();
	});

	app.get('/image/:id/view',function(req,res) {
		// return default view...		
		renderView("image", req, res)
	});

	app.get('/image/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("image", req, res)
	});

	// generated REST wrappers for entity 'video'

	// api.video.find
	app.get('/api/video/search', function(req, res) {
	 	api.video.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.video.count
	app.get('/api/video/count', function(req, res) {
	 	api.video.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.video.get
	app.get('/api/video/:id', function(req, res) {
	 	api.video.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.video.delete
	app.delete('/api/video/:id', function(req, res) {
	 	api.video.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.video.update
	app.put('/api/video/:id', function(req, res) {
		//api.video.update(req.params.id, req.body, function(err, rr) {
		api.video.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.video.create
	app.post('/api/video/new', function(req, res) {
		api.video.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/video',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/video.png" });
		res.end();
	});

	app.get('/video/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/video" });
		res.end();
	});

	app.get('/video/:id/view',function(req,res) {
		// return default view...		
		renderView("video", req, res)
	});

	app.get('/video/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("video", req, res)
	});

	// generated REST wrappers for entity 'voice'

	// api.voice.find
	app.get('/api/voice/search', function(req, res) {
	 	api.voice.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.voice.count
	app.get('/api/voice/count', function(req, res) {
	 	api.voice.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.voice.get
	app.get('/api/voice/:id', function(req, res) {
	 	api.voice.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.voice.delete
	app.delete('/api/voice/:id', function(req, res) {
	 	api.voice.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.voice.update
	app.put('/api/voice/:id', function(req, res) {
		//api.voice.update(req.params.id, req.body, function(err, rr) {
		api.voice.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.voice.create
	app.post('/api/voice/new', function(req, res) {
		api.voice.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/voice',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/voice.png" });
		res.end();
	});

	app.get('/voice/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/voice" });
		res.end();
	});

	app.get('/voice/:id/view',function(req,res) {
		// return default view...		
		renderView("voice", req, res)
	});

	app.get('/voice/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("voice", req, res)
	});

	// generated REST wrappers for entity 'json'

	// api.json.find
	app.get('/api/json/search', function(req, res) {
	 	api.json.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.json.count
	app.get('/api/json/count', function(req, res) {
	 	api.json.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.json.get
	app.get('/api/json/:id', function(req, res) {
	 	api.json.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.json.delete
	app.delete('/api/json/:id', function(req, res) {
	 	api.json.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.json.update
	app.put('/api/json/:id', function(req, res) {
		//api.json.update(req.params.id, req.body, function(err, rr) {
		api.json.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.json.create
	app.post('/api/json/new', function(req, res) {
		api.json.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/json',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/json.png" });
		res.end();
	});

	app.get('/json/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/json" });
		res.end();
	});

	app.get('/json/:id/view',function(req,res) {
		// return default view...		
		renderView("json", req, res)
	});

	app.get('/json/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("json", req, res)
	});

	// generated REST wrappers for entity 'netRadio'

	// api.netRadio.find
	app.get('/api/netRadio/search', function(req, res) {
	 	api.netRadio.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.netRadio.count
	app.get('/api/netRadio/count', function(req, res) {
	 	api.netRadio.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.netRadio.get
	app.get('/api/netRadio/:id', function(req, res) {
	 	api.netRadio.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.netRadio.delete
	app.delete('/api/netRadio/:id', function(req, res) {
	 	api.netRadio.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.netRadio.update
	app.put('/api/netRadio/:id', function(req, res) {
		//api.netRadio.update(req.params.id, req.body, function(err, rr) {
		api.netRadio.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.netRadio.create
	app.post('/api/netRadio/new', function(req, res) {
		api.netRadio.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/netRadio',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/netradio.png" });
		res.end();
	});

	app.get('/netRadio/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/netRadio" });
		res.end();
	});

	app.get('/netRadio/:id/view',function(req,res) {
		// return default view...		
		renderView("netRadio", req, res)
	});

	app.get('/netRadio/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("netRadio", req, res)
	});

	// generated REST wrappers for entity 'user'

	// api.user.find
	app.get('/api/user/search', function(req, res) {
	 	api.user.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.user.count
	app.get('/api/user/count', function(req, res) {
	 	api.user.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.user.get
	app.get('/api/user/:id', function(req, res) {
	 	api.user.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.user.delete
	app.delete('/api/user/:id', function(req, res) {
	 	api.user.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.user.update
	app.put('/api/user/:id', function(req, res) {
		//api.user.update(req.params.id, req.body, function(err, rr) {
		api.user.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.user.create
	app.post('/api/user/new', function(req, res) {
		api.user.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/user',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/user.png" });
		res.end();
	});

	app.get('/user/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/user" });
		res.end();
	});

	app.get('/user/:id/view',function(req,res) {
		// return default view...		
		renderView("user", req, res)
	});

	app.get('/user/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("user", req, res)
	});

	// generated REST wrappers for entity 'youTubeVideo'

	// api.youTubeVideo.find
	app.get('/api/youTubeVideo/search', function(req, res) {
	 	api.youTubeVideo.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.youTubeVideo.count
	app.get('/api/youTubeVideo/count', function(req, res) {
	 	api.youTubeVideo.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.youTubeVideo.get
	app.get('/api/youTubeVideo/:id', function(req, res) {
	 	api.youTubeVideo.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.youTubeVideo.delete
	app.delete('/api/youTubeVideo/:id', function(req, res) {
	 	api.youTubeVideo.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.youTubeVideo.update
	app.put('/api/youTubeVideo/:id', function(req, res) {
		//api.youTubeVideo.update(req.params.id, req.body, function(err, rr) {
		api.youTubeVideo.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.youTubeVideo.create
	app.post('/api/youTubeVideo/new', function(req, res) {
		api.youTubeVideo.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/youTubeVideo',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/youtubevideo.png" });
		res.end();
	});

	app.get('/youTubeVideo/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/youTubeVideo" });
		res.end();
	});

	app.get('/youTubeVideo/:id/view',function(req,res) {
		// return default view...		
		renderView("youTubeVideo", req, res)
	});

	app.get('/youTubeVideo/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("youTubeVideo", req, res)
	});

	// generated REST wrappers for entity 'file'

	// api.file.find
	app.get('/api/file/search', function(req, res) {
	 	api.file.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.file.count
	app.get('/api/file/count', function(req, res) {
	 	api.file.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.file.get
	app.get('/api/file/:id', function(req, res) {
	 	api.file.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.file.delete
	app.delete('/api/file/:id', function(req, res) {
	 	api.file.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.file.update
	app.put('/api/file/:id', function(req, res) {
		//api.file.update(req.params.id, req.body, function(err, rr) {
		api.file.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.file.create
	app.post('/api/file/new', function(req, res) {
		api.file.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/file',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/file.png" });
		res.end();
	});

	app.get('/file/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/file" });
		res.end();
	});

	app.get('/file/:id/view',function(req,res) {
		// return default view...		
		renderView("file", req, res)
	});

	app.get('/file/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("file", req, res)
	});

	// generated REST wrappers for entity 'entity'

	// api.entity.find
	app.get('/api/entity/search', function(req, res) {
	 	api.entity.find(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.entity.count
	app.get('/api/entity/count', function(req, res) {
	 	api.entity.count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.entity.get
	app.get('/api/entity/:id', function(req, res) {
	 	api.entity.get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.entity.delete
	app.delete('/api/entity/:id', function(req, res) {
	 	api.entity.delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	// api.entity.update
	app.put('/api/entity/:id', function(req, res) {
		//api.entity.update(req.params.id, req.body, function(err, rr) {
		api.entity.set(req.params.id, req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	// api.entity.create
	app.post('/api/entity/new', function(req, res) {
		api.entity.create(req.body, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/entity',function(req,res) {
		res.writeHead(302, {location: "/assets/thumbs/entity.png" });
		res.end();
	});

	app.get('/entity/:id/thumb',function(req,res) {
		var id = req.params.id
		console.log("Thumbnail: "+id)
		// default thumbnail:
		res.writeHead(302, {location: "/thumbs/entity" });
		res.end();
	});

	app.get('/entity/:id/view',function(req,res) {
		// return default view...		
		renderView("entity", req, res)
	});

	app.get('/entity/:id/preview',function(req,res) {
		// return default view...		
		renderPreview("entity", req, res)
	});

}