/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var scrapbookDAO = new (require("../dao/ScrapbookDAO"))

var ScrapbookAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("scrapbook", scrapbookDAO, {"color":"#abe"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ScrapbookAPI
