/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _scrapbookDAO = null
var scrapbookDAO = function() {
	if(!_scrapbookDAO) 
		_scrapbookDAO = require("../dao/ScrapbookDAO")
	return new (_scrapbookDAO)
}

var ScrapbookAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("scrapbook", scrapbookDAO, {"color":"#abe"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ScrapbookAPI