/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _shortcutDAO = null
var shortcutDAO = function() {
	if(!_shortcutDAO) 
		_shortcutDAO = require("../dao/ShortcutDAO")
	return new (_shortcutDAO)
}
var _shortcutTpl = null
var shortcutTpl = function() {
	if(!_shortcutTpl) 
		_shortcutTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/shortcut.default.html"), "utf8")
	return _shortcutTpl
}

var ShortcutAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("shortcut", shortcutDAO, shortcutTpl, {"color":"#bad"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ShortcutAPI