/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var shortcutDAO = new (require("../dao/ShortcutDAO"))

var ShortcutAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("shortcut", shortcutDAO, {"color":"#bad"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ShortcutAPI
