/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _shortcutDAO = null
var shortcutDAO = function() {
	if(!_shortcutDAO) 
		_shortcutDAO = require("../dao/ShortcutDAO")
	return new (_shortcutDAO)
}

var ShortcutAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("shortcut", shortcutDAO, {"color":"#bad"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ShortcutAPI