/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _themeDAO = null
var themeDAO = function() {
	if(!_themeDAO) 
		_themeDAO = require("../dao/ThemeDAO")
	return new (_themeDAO)
}

var ThemeAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("theme", themeDAO, {"color":"#bab"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = ThemeAPI