/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _usergroupDAO = null
var usergroupDAO = function() {
	if(!_usergroupDAO) 
		_usergroupDAO = require("../dao/UsergroupDAO")
	return new (_usergroupDAO)
}

var UsergroupAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("usergroup", usergroupDAO, {"color":"#cbe"})
	},
	getThumbnailUri: function(data) {		
		return this.thumbFromUUID(data.avatar)
	}
})

module.exports = UsergroupAPI