/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _usergroupUserDAO = null
var usergroupUserDAO = function() {
	if(!_usergroupUserDAO) 
		_usergroupUserDAO = require("../dao/UsergroupUserDAO")
	return new (_usergroupUserDAO)
}
var _usergroupUserTpl = null
var usergroupUserTpl = function() {
	if(!_usergroupUserTpl) 
		_usergroupUserTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/usergroupUser.default.html"), "utf8")
	return _usergroupUserTpl
}

var UsergroupUserAPI = NodeAPI.extend({
	constructor: function() {
		this.base("usergroupUser", usergroupUserDAO, usergroupUserTpl, {"color":"#ced"})
	},
	getThumbnailUri: function(data) {		
		return null
	}
})

module.exports = UsergroupUserAPI