/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var userAppSettingsDAO = new (require("../dao/UserAppSettingsDAO"))

var UserAppSettingsAPI = NodeAPI.extend({
	constructor: function() {
		this.base("userAppSettings", userAppSettingsDAO, {"color":"#ced"})
	},
	getThumbnailUri: function(data) {		
		return null
	},
	// store setting to the DB
	put: function(userId, appUUID, settings, next) {
		var self = this
		// remove all old settings...
		this.deleteItems({userId: userId, appUUID:appUUID}, function(err) {
			if(err) next(err);
			else if(settings) {
				self.create({userId:userId, appUUID:appUUID, settings:settings}, next)
			} else {
				next(null, null)
			}
		})
	},
	// get setting from the DB
	pull: function(userId, appUUID, next) {
		this.findOne({userId: userId, appUUID:appUUID}, next)
	}
})

module.exports = UserAppSettingsAPI
