/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _userDAO = null
var userDAO = function() {
	if(!_userDAO) 
		_userDAO = require("../dao/UserDAO")
	return new (_userDAO)
}
var _userTpl = null
var userTpl = function() {
	if(!_userTpl) 
		_userTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/user.default.html"), "utf8")
	return _userTpl
}

var UserAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("user", userDAO, userTpl)
	},
	getThumbnailUri: function(data) {		
		return this.thumbFromUUID(data.avatar)
	}
})

module.exports = UserAPI