/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var usergroupDAO = new(require("../dao/UsergroupDAO"))

var UsergroupAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("usergroup", usergroupDAO, {"color":"#cbe"})
	},
	getThumbnailUri: function(data) {		
		return this.thumbFromUUID(data.avatar)
	}
})

module.exports = UsergroupAPI
