/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _usergroupUserDAO = null
var usergroupUserDAO = function() {
	if(!_usergroupUserDAO) 
		_usergroupUserDAO = require("../dao/UsergroupUserDAO")
	return new (_usergroupUserDAO)
}

var UsergroupUserAPI = NodeAPI.extend({
	constructor: function() {
		this.base("usergroupUser", usergroupUserDAO, {"color":"#ced"})
	},
	getThumbnailUri: function(data) {		
		return null
	},
	// keeps only one entry of each value type (adminId, nodeId)
	addToGroup: function(usergroupId, userId, next) {
		var self = this
		self.removeFromGroup(usergroupId, userId, function(err, res) {
			if(err) next(err);
			else {
				var entry = {
					usergroupId: usergroupId,
					userId: userId
				}
				self.create(entry, next)	
			}
		})
	},
	removeFromGroup: function(usergroupId, userId, next) {
		this.deleteItems({usergroupId: usergroupId, userId:userId}, next)
	},
	getContents: function(usergroupId, next) {
		this.find({usergroupId: usergroupId}, next)
	}
})

module.exports = UsergroupUserAPI