/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _userFavNodeDAO = null
var userFavNodeDAO = function() {
	if(!_userFavNodeDAO) 
		_userFavNodeDAO = require("../dao/UserFavNodeDAO")
	return new (_userFavNodeDAO)
}

var UserFavNodeAPI = NodeAPI.extend({
	constructor: function() {
		this.base("userFavNode", userFavNodeDAO, {"color":"#ced"})
	},
	getThumbnailUri: function(data) {		
		return null
	},
	// keeps only one entry of each value type (adminId, nodeId)
	addToCollection: function(userId, nodeId, favorite, next) {
		var self = this
		this.eapi.getp(nodeId).done(function(data) {
			if(!data) {
				next(new Error("Node not found!"))
			} else {
				self.removeFromCollection(userId, nodeId, function(err, res) {
					if(err) next(err);
					else {
						var entry = {
							userId: userId,
							nodeId: nodeId,
							entityType: data.type,
							entityId: data.eid,
							favorite: favorite
						}
						self.create(entry, next)	
					}
				})
				
			}
		})

	},
	removeFromCollection: function(userId, nodeId, next) {
		this.deleteItems({userId: userId, nodeId:nodeId}, next)
	},
	getContents: function(userId, next) {
		this.find({userId: userId}, next)
	}})

module.exports = UserFavNodeAPI