/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var _videoDAO = null
var videoDAO = function() {
	if(!_videoDAO) 
		_videoDAO = require("../dao/VideoDAO")
	return new (_videoDAO)
}
var _videoTpl = null
var videoTpl = function() {
	if(!_videoTpl) 
		_videoTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/video.default.html"), "utf8")
	return _videoTpl
}

var FileAPI = require("./FileAPI")

var VideoAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("video", videoDAO, videoTpl, {"color":"#fdf"})
		this.fapi = new FileAPI()
	},
	getThumbnailUri: function(data) {		
		return this.thumbFromUUID(data.videoUUID)
	},
	get: function(id, next) {
		var self = this
		this.base(id, function(err, video) {
			if(err) next(err);
			else if(!video) next(null, null);
			else {
				self.fapi.getByUuid(video.videoUUID, function(err, vid) {
					video.video = vid
					next(null, video)
				})
			}
		})
	}

})

module.exports = VideoAPI