/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _videoDAO = null
var videoDAO = function() {
	if(!_videoDAO) 
		_videoDAO = require("../dao/VideoDAO")
	return new (_videoDAO)
}
var _videoTpl = null
var videoTpl = function() {
	if(!_videoTpl) 
		_videoTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/video.default.html"), "utf8")
	return _videoTpl
}

var VideoAPI = NodeAPI.extend({
	constructor: function() {
		this.base("video", videoDAO, videoTpl)
	},
	getThumbnailUri: function(data) {		
		return this.thumbFromUUID(data.videoUUID)
	}
})

module.exports = VideoAPI