/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var IndexedNodeAPI = require("./IndexedNodeAPI")

var voiceDAO = new(require("../dao/VoiceDAO"))

var FileAPI = require("./FileAPI")

var VoiceAPI = IndexedNodeAPI.extend({
	constructor: function() {
		this.base("voice", voiceDAO, {"color":"#dff"})
		this.fapi = new FileAPI()
	},
	getThumbnailUri: function(data) {		
		return this.thumbFromUUID(data.voiceUUID)
	},
	get: function(id, next) {
		var self = this
		this.base(id, function(err, voice) {
			if(err) next(err);
			else if(!voice) next(null, null);
			else {
				self.fapi.getByUuid(voice.voiceUUID, function(err, vc) {
					voice.voice = vc
					next(null, voice)
				})
			}
		})
	}
})

module.exports = VoiceAPI
