/* File autogenerated by craft  */

var fs = require('fs'); 
var path = require("path")
var NodeAPI = require("./NodeAPI")

var _youTubeVideoDAO = null
var youTubeVideoDAO = function() {
	if(!_youTubeVideoDAO) 
		_youTubeVideoDAO = require("../dao/YouTubeVideoDAO")
	return new (_youTubeVideoDAO)
}
var _youTubeVideoTpl = null
var youTubeVideoTpl = function() {
	if(!_youTubeVideoTpl) 
		_youTubeVideoTpl = fs.readFileSync(path.join(__dirname, "../../templates/nodes/youTubeVideo.default.html"), "utf8")
	return _youTubeVideoTpl
}

var YouTubeVideoAPI = NodeAPI.extend({
	constructor: function() {
		this.base("youTubeVideo", youTubeVideoDAO, youTubeVideoTpl)
	},
	getThumbnailUri: function() {
		return null
	}
})

module.exports = YouTubeVideoAPI