/* File autogenerated by craft  */

var _ = require("lodash")
var fs = require("fs-extra")
var merge = require("merge")

module.exports = function(app, api, Auth) {


	// helper function to return the results
	var out = function(res, err, rr) {
    	if(!err) {
    		res.json(rr)
    	} else {
    		console.error(err)
    		res.json({ error: err })
    	}
	}

	var renderView = function(name, req, res) {
		api[name].get(req.params.id, function(err, rr) {
	    	if(!err) {
	    		if(!rr) {
	    			res.status(404)
	    			res.end('not found')
	    			return
	    		}
				var tpl = api[name].renderView(rr)
				res.render('nodeview', { 
					layout: 'master', 
					view: tpl, 
					title: rr.title,
					created: rr.created,
					tags: rr.tags,
					description: rr.description,
					typeThumbnailUrl: api[name].getTypeThumbnailUri(),
					typeTitle: api[name].metadata.title,
					thumbnailUrl: api[name].getThumbnailUri(rr) || api[name].getTypeThumbnailUri()
				 })
    			// res.send(tpl)
    		} else {
    			console.error(err)
    			res.status(500);
    			res.end('error')
    		}
	  	})	
	}		

	var renderPreview = function(name, req, res) {
		api[name].get(req.params.id, function(err, rr) {
	    	if(!err) {
	    		if(!rr) {
	    			res.status(404)
	    			res.end('not found')
	    			return
	    		}
	    		var opts = null
	    		if(req.query.view) {
	    			opts = { previewType: req.query.view }
	    		}
				var tpl = api[name].renderPreview(rr, opts)
    			res.send(tpl)
    		} else {
    			console.error(err)
    			res.status(500);
    			res.end('error')
    		}
	  	})	
	}		
	
	// common functionality for all API calls
	// returned data are in JSON
	app.use("/api", function(req, res, next) {
		res.type('application/json');
		next()
	})
	
	// get entity schema, default vals object and other useful stuff
	app.get('/api/:type/metainfo', function(req, res) {
		var metainfo = api[req.params.type].getMetaInfo()
	    out(res, null, metainfo)
	})

	app.get('/api/:type/search', Auth.isAuthenticatedAsAdmin, function(req, res) {
		var ownerAdminId = req.user.admin._id		
		var type = req.params.type
		var query = req.query
		var q = {
			limit: parseInt(query.limit || 10),
			skip: parseInt(query.skip || 0),
			sort: { 'title': 'asc' },
			query: { ownerAdminId: ownerAdminId }
		}
	 	console.log("Finding items: "+type)
	 	api[type].findWithOptions(q, function(err, rr) {
	    	out(res, err, rr)
	  	})		  	
	});

	app.get('/api/:type/count', function(req, res) {
		var type = req.params.type
	 	api[type].count(req.query, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	app.get('/api/:type/personal', Auth.isAuthenticatedAsUser, function(req, res) {
		var type = req.params.type
		var query = req.query
		var userId = parseInt(req.user.user._id)
		var q = {
			limit: parseInt(query.limit || 10),
			skip: parseInt(query.skip || 0),
			sort: { 'title': 'asc' },
			query: { type: type, userId: userId }
		}
	 	console.log("Finding personal items: "+type)
	 	api.favorite.findWithOptions(q, function(err, rr) {
	 		var ids = _.map(rr, function(r) {return r.eid})
	 		api[type].getMultip(ids).done(function(items) {
	 			out(res, null, items)	
	 		})
	  	})		  	
	});

	app.get('/api/:type/favorite', Auth.isAuthenticatedAsUser, function(req, res) {
		var type = req.params.type
		var query = req.query
		var userId = parseInt(req.user.user._id)
		var q = {
			limit: parseInt(query.limit || 10),
			skip: parseInt(query.skip || 0),
			sort: { 'title': 'asc' },
			query: { type: type, userId: userId, favorite: true }
		}
	 	console.log("Finding favorite items: "+type)
	 	api.favorite.findWithOptions(q, function(err, rr) {
	 		var ids = _.map(rr, function(r) {return r.eid})
	 		api[type].getMultip(ids).done(function(items) {
	 			out(res, null, items)	
	 		})
	 	})
	});

	// TODO specific routes for image, video, voice
	app.get('/api/:type/:id', function(req, res) {
		var type = req.params.type
	 	api[type].get(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	app.delete('/api/:type/:id', Auth.isAuthenticatedAsAdmin, function(req, res) {
		var type = req.params.type
	 	api[type].delete(req.params.id, function(err, rr) {
	    	out(res, err, rr)
	  	})	
	});

	app.put('/api/:type/:id', Auth.isAuthenticatedAsAdmin, function(req, res) {
		var type = req.params.type
		var ownerAdminId = parseInt(req.user.admin._id)
		// TODO check if the resource is mine...
		// TODO make this as middleware
		var data = req.body
		api[type].set(req.params.id, data, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	
	 
	app.post('/api/:type/new', Auth.isAuthenticatedAsAdmin, function(req, res) {
		var type = req.params.type
		var data = merge({}, req.body)
		data.ownerAdminId = parseInt(req.user.admin._id)
		api[type].create(data, function(err, rr) {
	    	out(res, err, rr)
	  	})
	});	

	app.get('/thumbs/:type',function(req,res) {
		var type = req.params.type
		res.redirect("/assets/thumbs/"+type+".png");
	});

	app.get('/thumbs/:type/:id',function(req,res) {
		var type = req.params.type
		res.redirect("/thumbs/"+type);
	});

	app.get('/preview/:type/:id',function(req,res) {
		var type = req.params.type
		renderPreview(type, req, res)
	});

	app.get('/view/:type/:id',function(req,res) {
		var type = req.params.type
		renderView(type, req, res)
	});

}