/* File autogenerated by craft {{datetime}} */

var merge = require("merge")
var fs = require('fs'); // require the filesystem api
var path = require("path")
var mustache = require("mustache")
var Base = require("basejs")

{{#daos}}
var {{apiname}} = require("./{{apiname}}")
{{/daos}}

var API = {
	{{#daos}}
	{{name}}: new {{apiname}}(),
	{{/daos}}
}

module.exports = API