/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/admin.defaults.json")

var schema = require("../../entity/admin.schema.json")

/**
 * ## AdminDAO
 * Administrator profile.
 */
var AdminDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("admins"), schema, defaults)
	},
	update: function(data, next) {
		this.base(data, next)
	}
})})

module.exports = AdminDAO

