/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/admin.defaults.json")

var schema = require("../../entity/admin.schema.json")

/**
 * ## AdminDAO
 * Administrator profile.
 */
var AdminDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("admins"), schema, defaults)
	}
})

module.exports = AdminDAO

