/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/album.defaults.json")

var schema = require("../../entity/album.schema.json")

/**
 * ## AlbumDAO
 * Album
 */
var AlbumDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("albums"), schema, defaults)
	}
})

module.exports = AlbumDAO

