/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/app.defaults.json")

var schema = require("../../entity/app.schema.json")

/**
 * ## AppDAO
 * Imported App
 */
var AppDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("apps"), schema, defaults)
	}
})

module.exports = AppDAO

