/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/article.defaults.json")

var schema = require("../../entity/article.schema.json")

/**
 * ## ArticleDAO
 * Text article.
 */
var ArticleDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("articles"), schema, defaults)
	}
})

module.exports = ArticleDAO

