/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/drawing.defaults.json")

var schema = require("../../entity/drawing.schema.json")

/**
 * ## DrawingDAO
 * JSON Data.
 */
var DrawingDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("drawings"), schema, defaults)
	}
})

module.exports = DrawingDAO

