/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/entity.defaults.json")

var schema = require("../../entity/entity.schema.json")

/**
 * ## EntityDAO
 * Abstract entity.
 */
var EntityDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("entities"), schema, defaults)
	}
})

module.exports = EntityDAO

