/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/favorite.defaults.json")

var schema = require("../../entity/favorite.schema.json")

/**
 * ## JsonDAO
 * JSON Data.
 */
var FavoriteDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("favorites"), schema, defaults)
	}
})

module.exports = FavoriteDAO

