/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/file.defaults.json")

var schema = require("../../entity/file.schema.json")

/**
 * ## FileDAO
 * Uploaded file.
 */
var FileDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("files"), schema, defaults)
	}
})

module.exports = FileDAO

