/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/image.defaults.json")

var schema = require("../../entity/image.schema.json")

/**
 * ## ImageDAO
 * Image.
 */
var ImageDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("images"), schema, defaults)
	}
})

module.exports = ImageDAO

