var Storage = require("../storage")
var crud = Storage.crud("imports")
var dateFormat = require('dateformat')

var Imports = {
	create: function(adminId, data, cb) {
		var date = new Date()
		var obj = {
			// default manifest
			apptype: "basic", // default value
			title: "Imported Application",
			description: "",
			author: "",
			version: "",
			uri: "",
			created: dateFormat(date, "isoDateTime"),
			autogenerated: true,
			adminId: adminId
		}
		for(var key in data) obj[key] = data[key]
		crud.create(obj, cb)
	},
	update: function(data, cb) {
		crud.update(data, cb)
	},
	remove: function(importId, cb) {
		crud.remove(importId, cb)
	},
	get: function(importId, cb) {
		crud.get(importId, cb)
	},
	list: function(adminId, start, limit, cb) {
		crud.find({adminId:adminId})
			.sort({"title":"asc"})
			.limit(limit)
			.skip(start)
			.toArray(cb)
	}
}

module.exports = Imports

