/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/json.defaults.json")

var schema = require("../../entity/json.schema.json")

/**
 * ## JsonDAO
 * JSON Data.
 */
var JsonDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("jsons"), schema, defaults)
	}
})

module.exports = JsonDAO

