/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/layout.defaults.json")

var schema = require("../../entity/layout.schema.json")

/**
 * ## LayoutDAO
 */
var LayoutDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("layouts"), schema, defaults)
	}
})

module.exports = LayoutDAO

