/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/log.defaults.json")

var schema = require("../../entity/log.schema.json")

/**
 * ## JsonDAO
 * JSON Data.
 */
var LogDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("logs"), schema, defaults)
	}
})

module.exports = LogDAO

