/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/playlistNode.defaults.json")

var schema = require("../../entity/playlistNode.schema.json")

/**
 * ## AlbumNodeDAO
 * AlbumNode
 */
var PlaylistNodeDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("playlistNodes"), schema, defaults)
	}
})

module.exports = PlaylistNodeDAO

