/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/playlist.defaults.json")

var schema = require("../../entity/playlist.schema.json")

/**
 * ## JsonDAO
 * JSON Data.
 */
var PlaylistDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("playlists"), schema, defaults)
	}
})

module.exports = PlaylistDAO

