/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/scrapbook.defaults.json")

var schema = require("../../entity/scrapbook.schema.json")

/**
 * ## ScrapbookDAO
 * Scrapbook
 */
var ScrapbookDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("scrapbooks"), schema, defaults)
	}
})

module.exports = ScrapbookDAO

