/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/theme.defaults.json")

var schema = require("../../entity/theme.schema.json")

/**
 * ## ThemeDAO
 * Theme
 */
var ThemeDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("themes"), schema, defaults)
	}
})

module.exports = ThemeDAO

