/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/userAppSettings.defaults.json")

var schema = require("../../entity/userAppSettings.schema.json")

/**
 * ## UserFavNodeDAO
 * UserFavNode
 */
var UserAppSettingsDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("userAppSettings"), schema, defaults)
	}
})

module.exports = UserAppSettingsDAO

