/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/user.defaults.json")

var schema = require("../../entity/user.schema.json")

/**
 * ## UserDAO
 * User profile.
 */
var UserDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("users"), schema, defaults)
	}
})

module.exports = UserDAO

