/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/userFavNode.defaults.json")

var schema = require("../../entity/userFavNode.schema.json")

/**
 * ## UserFavNodeDAO
 * UserFavNode
 */
var UserFavNodeDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("userFavNodes"), schema, defaults)
	}
})

module.exports = UserFavNodeDAO

