/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/video.defaults.json")

var schema = require("../../entity/video.schema.json")

/**
 * ## VideoDAO
 * Video clip.
 */
var VideoDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("videos"), schema, defaults)
	}
})

module.exports = VideoDAO

