/* File autogenerated by craft  */

var Storage = require("../Storage")
var NodeDAO = require("./NodeDAO")

var defaults = require("../../entity/voice.defaults.json")

var schema = require("../../entity/voice.schema.json")

/**
 * ## VoiceDAO
 * Audio clip.
 */
var VoiceDAO = NodeDAO.extend({
	constructor: function() {
		this.base(Storage.collection("voices"), schema, defaults)
	}
})

module.exports = VoiceDAO

