/* File autogenerated by craft  */

var Storage = require("../Storage")
var SchemedDAO = require("./SchemedDAO")

var defaults = require("../../entity/youTubeVideo.defaults.json")

var schema = require("../../entity/youTubeVideo.schema.json")

/**
 * ## YouTubeVideoDAO
 * YouTube Video.
 */
var YouTubeVideoDAO = SchemedDAO.extend({
	constructor: function() {
		this.base(Storage.collection("youtubevideos"), schema, defaults)
	}
})

module.exports = YouTubeVideoDAO

